"""initial records table

Revision ID: 8fc93c85d7ff
Revises: 
Create Date: 2020-03-21 06:21:34.000497

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8fc93c85d7ff'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('records',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('country_iso', sa.String(length=100), nullable=True),
    sa.Column('country_name', sa.String(length=100), nullable=True),
    sa.Column('date', sa.DATE(), nullable=True),
    sa.Column('confirmed', sa.INTEGER(), nullable=True),
    sa.Column('deaths', sa.INTEGER(), nullable=True),
    sa.Column('recovered', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_records_country_iso'), 'records', ['country_iso'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_records_country_iso'), table_name='records')
    op.drop_table('records')
    # ### end Alembic commands ###
